// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.mediapool.grab.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Movie_Roo_Configurable {
    
    declare @type: Movie: @Configurable;
    
}
