package de.mediapool.web.client;

import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window.Notification;

import de.mediapool.web.client.data.MediaContainer;
import de.mediapool.web.client.data.SearchFilter;
import de.mediapool.web.client.ui.HelpWindow;
import de.mediapool.web.client.ui.ListView;
import de.mediapool.web.client.ui.MediaForm;
import de.mediapool.web.client.ui.MediaList;
import de.mediapool.web.client.ui.NavigationTree;
import de.mediapool.web.client.ui.SearchView;
import de.mediapool.web.client.ui.SharingOptions;

/**
 */

public class WebEntityManagerView extends CustomComponent implements ClickListener, ValueChangeListener,
		ItemClickListener {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private NavigationTree tree = new NavigationTree(this);

	private Button newContact = new Button("Add contact");
	private Button search = new Button("Search");
	private Button share = new Button("Share");
	private Button help = new Button("Help");
	private HorizontalSplitPanel mainhoSplit = new HorizontalSplitPanel();

	// Lazyly created ui references
	private ListView listView = null;
	private SearchView searchView = null;
	private MediaList personList = null;
	private MediaForm personForm = null;
	private HelpWindow helpWindow = null;
	private SharingOptions sharingOptions = null;

	private MediaContainer dataSource = MediaManagerService.getMediaContainer();

	/**
	 * First build the main layout and set the composition root to support the
	 * visual editor. Then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor, and may be edited by the developer.
	 */
	public WebEntityManagerView() {
		setSizeFull();

		// build the layout based on the visual editor
		buildMainLayout();
		setMainPanel(getListView());

	}

	private void setMainPanel(Component c) {
		mainhoSplit.setSecondComponent(c);
	}

	private void buildMainLayout() {

		VerticalLayout layout = new VerticalLayout();
		layout.setSizeFull();
		setCompositionRoot(layout);
		layout.addComponent(createToolbar());
		layout.addComponent(mainhoSplit);
		layout.setExpandRatio(mainhoSplit, 1);

		mainhoSplit.setSplitPosition(200, HorizontalSplitPanel.UNITS_PIXELS);
		mainhoSplit.setFirstComponent(tree);

	}

	private HorizontalLayout createToolbar() {
		HorizontalLayout lo = new HorizontalLayout();
		lo.addComponent(newContact);
		lo.addComponent(search);
		lo.addComponent(share);
		lo.addComponent(help);

		search.addListener((ClickListener) this);
		share.addListener((ClickListener) this);
		help.addListener((ClickListener) this);
		newContact.addListener((ClickListener) this);

		search.setIcon(new ThemeResource("icons/32/folder-add.png"));
		share.setIcon(new ThemeResource("icons/32/users.png"));
		help.setIcon(new ThemeResource("icons/32/help.png"));
		newContact.setIcon(new ThemeResource("icons/32/document-add.png"));

		lo.setMargin(true);
		lo.setSpacing(true);

		lo.setStyleName("toolbar");

		lo.setWidth("100%");

		Embedded em = new Embedded("", new ThemeResource("images/logo.png"));
		lo.addComponent(em);
		lo.setComponentAlignment(em, Alignment.MIDDLE_RIGHT);
		lo.setExpandRatio(em, 1);

		return lo;
	}

	/*
	 * View getters exist so we can lazily generate the views, resulting in
	 * faster application startup time.
	 */
	private ListView getListView() {
		if (listView == null) {
			personList = new MediaList(this);
			personForm = new MediaForm(this);
			listView = new ListView(personList, personForm);
		}
		return listView;
	}

	private SearchView getSearchView() {
		if (searchView == null) {
			searchView = new SearchView(this);
		}
		return searchView;
	}

	private HelpWindow getHelpWindow() {
		if (helpWindow == null) {
			helpWindow = new HelpWindow();
		}
		return helpWindow;
	}

	private SharingOptions getSharingOptions() {
		if (sharingOptions == null) {
			sharingOptions = new SharingOptions();
		}
		return sharingOptions;
	}

	public MediaContainer getDataSource() {
		return dataSource;
	}

	public void buttonClick(ClickEvent event) {
		final Button source = event.getButton();

		if (source == search) {
			showSearchView();
		} else if (source == help) {
			showHelpWindow();
		} else if (source == share) {
			showShareWindow();
		} else if (source == newContact) {
			addNewContanct();
		}
	}

	private void showHelpWindow() {
		getApplication().getMainWindow().addWindow(getHelpWindow());
	}

	private void showShareWindow() {
		getApplication().getMainWindow().addWindow(getSharingOptions());
	}

	private void showListView() {
		setMainPanel(getListView());
	}

	private void showSearchView() {
		setMainPanel(getSearchView());
	}

	public void valueChange(ValueChangeEvent event) {
		Property property = event.getProperty();
		if (property == personList) {
			Item item = personList.getItem(personList.getValue());
			if (item != personForm.getItemDataSource()) {
				personForm.setItemDataSource(item);
			}
		}
	}

	public void itemClick(ItemClickEvent event) {
		if (event.getSource() == tree) {
			Object itemId = event.getItemId();
			if (itemId != null) {
				if (NavigationTree.SHOW_ALL.equals(itemId)) {
					// clear previous filters
					getDataSource().removeAllContainerFilters();
					showListView();
				} else if (NavigationTree.SEARCH.equals(itemId)) {
					showSearchView();
				} else if (itemId instanceof SearchFilter) {
					search((SearchFilter) itemId);
				}
			}
		}
	}

	private void addNewContanct() {
		showListView();
		personForm.addContact();
	}

	public void search(SearchFilter searchFilter) {
		// clear previous filters
		getDataSource().removeAllContainerFilters();
		// filter contacts with given filter
		getDataSource().addContainerFilter(searchFilter.getPropertyId(), searchFilter.getTerm(), true, false);
		showListView();

		getApplication().getMainWindow().showNotification(
				"Searched for " + searchFilter.getPropertyId() + "=*" + searchFilter.getTerm() + "*, found "
						+ getDataSource().size() + " item(s).", Notification.TYPE_TRAY_NOTIFICATION);
	}

	public void saveSearch(SearchFilter searchFilter) {
		tree.addItem(searchFilter);
		tree.setParent(searchFilter, NavigationTree.SEARCH);
		// mark the saved search as a leaf (cannot have children)
		tree.setChildrenAllowed(searchFilter, false);
		// make sure "Search" is expanded
		tree.expandItem(NavigationTree.SEARCH);
		// select the saved search
		tree.setValue(searchFilter);
	}

}
