// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package entity;

import entity.Movie;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect MovieDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MovieDataOnDemand: @Component;
    
    private Random MovieDataOnDemand.rnd = new SecureRandom();
    
    private List<Movie> MovieDataOnDemand.data;
    
    public Movie MovieDataOnDemand.getNewTransientMovie(int index) {
        Movie obj = new Movie();
        setApprovedage(obj, index);
        setCarrier(obj, index);
        setContenttype(obj, index);
        setCover(obj, index);
        setDescription(obj, index);
        setDuration(obj, index);
        setEan(obj, index);
        setGenre(obj, index);
        setLaunchyear(obj, index);
        setNumberdiscs(obj, index);
        setOriginaltitle(obj, index);
        setPrice(obj, index);
        setSpecial(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void MovieDataOnDemand.setApprovedage(Movie obj, int index) {
        int approvedage = index;
        obj.setApprovedage(approvedage);
    }
    
    public void MovieDataOnDemand.setCarrier(Movie obj, int index) {
        String carrier = "carrier_" + index;
        obj.setCarrier(carrier);
    }
    
    public void MovieDataOnDemand.setContenttype(Movie obj, int index) {
        String contenttype = "contenttype_" + index;
        obj.setContenttype(contenttype);
    }
    
    public void MovieDataOnDemand.setCover(Movie obj, int index) {
        String cover = "cover_" + index;
        obj.setCover(cover);
    }
    
    public void MovieDataOnDemand.setDescription(Movie obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void MovieDataOnDemand.setDuration(Movie obj, int index) {
        int duration = index;
        obj.setDuration(duration);
    }
    
    public void MovieDataOnDemand.setEan(Movie obj, int index) {
        String ean = "ean_" + index;
        obj.setEan(ean);
    }
    
    public void MovieDataOnDemand.setGenre(Movie obj, int index) {
        String genre = "genre_" + index;
        obj.setGenre(genre);
    }
    
    public void MovieDataOnDemand.setLaunchyear(Movie obj, int index) {
        String launchyear = "launchyear_" + index;
        obj.setLaunchyear(launchyear);
    }
    
    public void MovieDataOnDemand.setNumberdiscs(Movie obj, int index) {
        int numberdiscs = index;
        obj.setNumberdiscs(numberdiscs);
    }
    
    public void MovieDataOnDemand.setOriginaltitle(Movie obj, int index) {
        String originaltitle = "originaltitle_" + index;
        obj.setOriginaltitle(originaltitle);
    }
    
    public void MovieDataOnDemand.setPrice(Movie obj, int index) {
        double price = new Integer(index).doubleValue();
        obj.setPrice(price);
    }
    
    public void MovieDataOnDemand.setSpecial(Movie obj, int index) {
        String special = "special_" + index;
        obj.setSpecial(special);
    }
    
    public void MovieDataOnDemand.setTitle(Movie obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public Movie MovieDataOnDemand.getSpecificMovie(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Movie obj = data.get(index);
        return Movie.findMovie(obj.getId());
    }
    
    public Movie MovieDataOnDemand.getRandomMovie() {
        init();
        Movie obj = data.get(rnd.nextInt(data.size()));
        return Movie.findMovie(obj.getId());
    }
    
    public boolean MovieDataOnDemand.modifyMovie(Movie obj) {
        return false;
    }
    
    public void MovieDataOnDemand.init() {
        data = Movie.findMovieEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Movie' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<entity.Movie>();
        for (int i = 0; i < 10; i++) {
            Movie obj = getNewTransientMovie(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
