package de.mediapool.web.ui;

import de.mediapool.web.EntityEditor;
import entity.Movie;
import entity.meta.Participation;
import entity.select.Award;
import entity.select.MLanguage;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import org.vaadin.addon.customfield.ConvertingValidator;
import org.vaadin.addon.customfield.PropertyConverter;
import org.vaadin.addon.customfield.beanfield.BeanSetFieldPropertyConverter;

import com.vaadin.addon.beanvalidation.BeanValidationValidator;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Container;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Validator;
import com.vaadin.data.util.BeanContainer;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.terminal.UserError;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.AbstractSelect;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Field;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.VerticalLayout;


/**
 * Form for editing an entity. The layout of this form can be edited with the
 * Vaadin Visual Editor.
 * 
 * Fields are automatically bound to container data sources and item properties
 * based on their names (propertyId + "Field") in the aspect. Implementing
 * methods with the same name as used in the aspect allows "overriding"
 * functionality as such methods replace those from the aspect.
 */
public class MovieForm extends CustomComponent implements EntityEditor {

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private Panel scrollPanel;
    @AutoGenerated
    private VerticalLayout scrollContent;
    @AutoGenerated
    private HorizontalLayout buttonLayout;
    @AutoGenerated
    private Button deleteButton;
    @AutoGenerated
    private Button cancelButton;
    @AutoGenerated
    private Button saveButton;
	@AutoGenerated
	private Label errorMessageLabel;
    @AutoGenerated
    private VerticalLayout fieldLayout;
    @AutoGenerated
    private TextField titleField;
    @AutoGenerated
    private TextField originaltitleField;
    @AutoGenerated
    private TextField launchyearField;
    @AutoGenerated
    private TextField coverField;
    @AutoGenerated
    private TextField priceField;
    @AutoGenerated
    private TextField eanField;
    @AutoGenerated
    private TextField descriptionField;
    @AutoGenerated
    private TextField specialField;
    @AutoGenerated
    private TextField contenttypeField;
    @AutoGenerated
    private TextField genreField;
    @AutoGenerated
    private TextField carrierField;
    @AutoGenerated
    private TwinColSelect mlanguageField;
    @AutoGenerated
    private TwinColSelect awardField;
    @AutoGenerated
    private TwinColSelect participationField;
    @AutoGenerated
    private TextField durationField;
    @AutoGenerated
    private TextField numberdiscsField;
    @AutoGenerated
    private TextField approvedageField;


    // data item being edited
    private Item item;

    public MovieForm() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        configure();

        // make saving the form the default action on Enter keypress
        saveButton.setClickShortcut(KeyCode.ENTER);

        // TODO add user code here
    }

    public void addSaveActionListener(ClickListener listener) {
        saveButton.addListener(listener);
    }

    public void addCancelActionListener(ClickListener listener) {
        cancelButton.addListener(listener);
    }

    public void addDeleteActionListener(ClickListener listener) {
        deleteButton.addListener(listener);
    }

    public void setSaveAllowed(boolean canSave) {
        saveButton.setVisible(canSave);
        cancelButton.setVisible(canSave);
        saveButton.setEnabled(canSave);
        cancelButton.setEnabled(canSave);

        // do not change the enabled state of the delete button
        fieldLayout.setEnabled(canSave);
    }

    public void setDeleteAllowed(boolean canDelete) {
        deleteButton.setVisible(canDelete);
        deleteButton.setEnabled(canDelete);
    }

    public void setCommitErrorMessage(String message) {
        errorMessageLabel.setVisible(message != null);
   	    errorMessageLabel.setValue(message);
    }

    public void commit() {
        if (getItemDataSource() != null) {
            validateFields();
            setCommitErrorMessage(null);
            commitFields();
        }
    }

    public void setItemDataSource(Item item) {
        // TODO implement

        this.item = item;

        setFieldValues(item);
        setCommitErrorMessage(null);
    }

    public Item getItemDataSource() {
        return item;
    }

    @Override
    public void focus() {
        Field field = getFirstField();
        if (field != null) {
            field.focus();
        }
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // scrollPanel
        scrollPanel = buildScrollPanel();
        mainLayout.addComponent(scrollPanel);

        return mainLayout;
    }

    @AutoGenerated
    private Panel buildScrollPanel() {
        // common part: create layout
        scrollPanel = new Panel();
        scrollPanel.setWidth("100.0%");
        scrollPanel.setHeight("100.0%");
        scrollPanel.setImmediate(false);

        // scrollContent
        scrollContent = buildScrollContent();
        scrollPanel.setContent(scrollContent);

        return scrollPanel;
    }

    @AutoGenerated
    private VerticalLayout buildScrollContent() {
        // common part: create layout
        scrollContent = new VerticalLayout();
        scrollContent.setWidth("100.0%");
        scrollContent.setHeight("-1px");
        scrollContent.setImmediate(false);
        scrollContent.setMargin(true);
        scrollContent.setSpacing(true);

        // fieldLayout
        fieldLayout = buildFieldLayout();
        scrollContent.addComponent(fieldLayout);

		// errorMessageLabel
		errorMessageLabel = new Label();
		errorMessageLabel.setWidth("-1px");
		errorMessageLabel.setHeight("-1px");
		errorMessageLabel.setStyleName("errormessage");
		errorMessageLabel.setValue("");
		errorMessageLabel.setImmediate(false);
		scrollContent.addComponent(errorMessageLabel);

        // buttonLayout
        buttonLayout = buildButtonLayout();
        scrollContent.addComponent(buttonLayout);

        return scrollContent;
    }

    @AutoGenerated
    private VerticalLayout buildFieldLayout() {
        // common part: create layout
        fieldLayout = new VerticalLayout();
        fieldLayout.setWidth("100.0%");
        fieldLayout.setHeight("-1px");
        fieldLayout.setImmediate(false);
        fieldLayout.setMargin(false);
        fieldLayout.setSpacing(true);

        // titleField
        titleField = new TextField();
        titleField.setWidth("-1px");
        titleField.setHeight("-1px");
        titleField.setCaption("Title");
        titleField.setImmediate(true);
        fieldLayout.addComponent(titleField);

        // originaltitleField
        originaltitleField = new TextField();
        originaltitleField.setWidth("-1px");
        originaltitleField.setHeight("-1px");
        originaltitleField.setCaption("Originaltitle");
        originaltitleField.setImmediate(true);
        fieldLayout.addComponent(originaltitleField);

        // launchyearField
        launchyearField = new TextField();
        launchyearField.setWidth("-1px");
        launchyearField.setHeight("-1px");
        launchyearField.setCaption("Launchyear");
        launchyearField.setImmediate(true);
        fieldLayout.addComponent(launchyearField);

        // coverField
        coverField = new TextField();
        coverField.setWidth("-1px");
        coverField.setHeight("-1px");
        coverField.setCaption("Cover");
        coverField.setImmediate(true);
        fieldLayout.addComponent(coverField);

        // priceField
        priceField = new TextField();
        priceField.setWidth("-1px");
        priceField.setHeight("-1px");
        priceField.setCaption("Price");
        priceField.setImmediate(true);
        fieldLayout.addComponent(priceField);

        // eanField
        eanField = new TextField();
        eanField.setWidth("-1px");
        eanField.setHeight("-1px");
        eanField.setCaption("Ean");
        eanField.setImmediate(true);
        fieldLayout.addComponent(eanField);

        // descriptionField
        descriptionField = new TextField();
        descriptionField.setWidth("-1px");
        descriptionField.setHeight("-1px");
        descriptionField.setCaption("Description");
        descriptionField.setImmediate(true);
        fieldLayout.addComponent(descriptionField);

        // specialField
        specialField = new TextField();
        specialField.setWidth("-1px");
        specialField.setHeight("-1px");
        specialField.setCaption("Special");
        specialField.setImmediate(true);
        fieldLayout.addComponent(specialField);

        // contenttypeField
        contenttypeField = new TextField();
        contenttypeField.setWidth("-1px");
        contenttypeField.setHeight("-1px");
        contenttypeField.setCaption("Contenttype");
        contenttypeField.setImmediate(true);
        fieldLayout.addComponent(contenttypeField);

        // genreField
        genreField = new TextField();
        genreField.setWidth("-1px");
        genreField.setHeight("-1px");
        genreField.setCaption("Genre");
        genreField.setImmediate(true);
        fieldLayout.addComponent(genreField);

        // carrierField
        carrierField = new TextField();
        carrierField.setWidth("-1px");
        carrierField.setHeight("-1px");
        carrierField.setCaption("Carrier");
        carrierField.setImmediate(true);
        fieldLayout.addComponent(carrierField);

        // mlanguageField
        mlanguageField = new TwinColSelect();
        mlanguageField.setWidth("-1px");
        mlanguageField.setHeight("-1px");
        mlanguageField.setCaption("Mlanguage");
        mlanguageField.setImmediate(true);
        fieldLayout.addComponent(mlanguageField);

        // awardField
        awardField = new TwinColSelect();
        awardField.setWidth("-1px");
        awardField.setHeight("-1px");
        awardField.setCaption("Award");
        awardField.setImmediate(true);
        fieldLayout.addComponent(awardField);

        // participationField
        participationField = new TwinColSelect();
        participationField.setWidth("-1px");
        participationField.setHeight("-1px");
        participationField.setCaption("Participation");
        participationField.setImmediate(true);
        fieldLayout.addComponent(participationField);

        // durationField
        durationField = new TextField();
        durationField.setWidth("-1px");
        durationField.setHeight("-1px");
        durationField.setCaption("Duration");
        durationField.setImmediate(true);
        fieldLayout.addComponent(durationField);

        // numberdiscsField
        numberdiscsField = new TextField();
        numberdiscsField.setWidth("-1px");
        numberdiscsField.setHeight("-1px");
        numberdiscsField.setCaption("Numberdiscs");
        numberdiscsField.setImmediate(true);
        fieldLayout.addComponent(numberdiscsField);

        // approvedageField
        approvedageField = new TextField();
        approvedageField.setWidth("-1px");
        approvedageField.setHeight("-1px");
        approvedageField.setCaption("Approvedage");
        approvedageField.setImmediate(true);
        fieldLayout.addComponent(approvedageField);


        return fieldLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildButtonLayout() {
        // common part: create layout
        buttonLayout = new HorizontalLayout();
        buttonLayout.setWidth("-1px");
        buttonLayout.setHeight("-1px");
        buttonLayout.setImmediate(false);
        buttonLayout.setMargin(false);
        buttonLayout.setSpacing(true);

        // saveButton
        saveButton = new Button();
        saveButton.setWidth("-1px");
        saveButton.setHeight("-1px");
        saveButton.setCaption("Save");
        saveButton.setStyleName("primary");
        saveButton.setImmediate(true);
        buttonLayout.addComponent(saveButton);

        // cancelButton
        cancelButton = new Button();
        cancelButton.setWidth("-1px");
        cancelButton.setHeight("-1px");
        cancelButton.setCaption("Cancel");
        cancelButton.setImmediate(true);
        buttonLayout.addComponent(cancelButton);

        // deleteButton
        deleteButton = new Button();
        deleteButton.setWidth("-1px");
        deleteButton.setHeight("-1px");
        deleteButton.setCaption("Delete");
        deleteButton.setStyleName("link");
        deleteButton.setImmediate(true);
        buttonLayout.addComponent(deleteButton);
        buttonLayout.setComponentAlignment(deleteButton, new Alignment(48));

        return buttonLayout;
    }


	private Map<Object, Field> fieldMap = new LinkedHashMap<Object, Field>();

	private Map<Object, PropertyConverter> converterMap = new LinkedHashMap<Object, PropertyConverter>();

	public Collection<Object> getBeanPropertyIds() {
        return Arrays.asList(new Object[] { "title", "originaltitle", "launchyear", "cover", "price", "ean", "description", "special", "contenttype", "genre", "carrier", "mlanguage", "award", "participation", "duration", "numberdiscs", "approvedage" });
    }

	public Field getField(Object propertyId) {
        return fieldMap.get(propertyId);
    }

	public void configure() {
        configureFieldMap();
        configureFields();
        configureContainersForFields();
        configureConverters();
        configureValidators();
    }

	public void refresh() {
        configureContainersForFields();
        configureConverters();
        configureValidators();
    }

	public boolean isModified() {
        if (getItemDataSource() != null) {
            for (Object propertyId : getItemDataSource().getItemPropertyIds()) {
                Field field = getField(propertyId);
                if (field != null && field.isModified()) {
                    return true;
                }
            }
        }
        return false;
    }

	public void configureFieldMap() {
        fieldMap.put("title", titleField);
        fieldMap.put("originaltitle", originaltitleField);
        fieldMap.put("launchyear", launchyearField);
        fieldMap.put("cover", coverField);
        fieldMap.put("price", priceField);
        fieldMap.put("ean", eanField);
        fieldMap.put("description", descriptionField);
        fieldMap.put("special", specialField);
        fieldMap.put("contenttype", contenttypeField);
        fieldMap.put("genre", genreField);
        fieldMap.put("carrier", carrierField);
        fieldMap.put("mlanguage", mlanguageField);
        fieldMap.put("award", awardField);
        fieldMap.put("participation", participationField);
        fieldMap.put("duration", durationField);
        fieldMap.put("numberdiscs", numberdiscsField);
        fieldMap.put("approvedage", approvedageField);
    }

	public void configureFields() {
        for (Object propertyId : getBeanPropertyIds()) {
            Field field = getField(propertyId);
            if (field == null) {
                continue;
            }
            if (field instanceof TextField) {
                ((TextField) field).setNullRepresentation("");
            }
            field.setWriteThrough(false);
            field.setInvalidAllowed(true);
        }
    }

	public void configureContainersForFields() {
        Field field;
        
        field = getField("mlanguage");
        if (field instanceof AbstractSelect) {
            ((AbstractSelect) field).setContainerDataSource(getContainerForMLanguages());
            Object captionId = getMLanguageCaptionPropertyId();
            if (captionId != null) {
                ((AbstractSelect) field).setItemCaptionPropertyId(captionId);
            } else {
                ((AbstractSelect) field).setItemCaptionMode(AbstractSelect.ITEM_CAPTION_MODE_ITEM);
            }
        }
        
        field = getField("participation");
        if (field instanceof AbstractSelect) {
            ((AbstractSelect) field).setContainerDataSource(getContainerForParticipations());
            Object captionId = getParticipationCaptionPropertyId();
            if (captionId != null) {
                ((AbstractSelect) field).setItemCaptionPropertyId(captionId);
            } else {
                ((AbstractSelect) field).setItemCaptionMode(AbstractSelect.ITEM_CAPTION_MODE_ITEM);
            }
        }
        
        field = getField("award");
        if (field instanceof AbstractSelect) {
            ((AbstractSelect) field).setContainerDataSource(getContainerForAwards());
            Object captionId = getAwardCaptionPropertyId();
            if (captionId != null) {
                ((AbstractSelect) field).setItemCaptionPropertyId(captionId);
            } else {
                ((AbstractSelect) field).setItemCaptionMode(AbstractSelect.ITEM_CAPTION_MODE_ITEM);
            }
        }
    }

	public void configureConverters() {
        // cannot parametrize PropertyConverter here due to an AJDT bug
        PropertyConverter converter;
        Container container;
        Field field;
        
        field = getField("mlanguage");
        if (field instanceof AbstractSelect) {
            container = ((AbstractSelect) field).getContainerDataSource();
            converter = new BeanSetFieldPropertyConverter<MLanguage, Long>(MLanguage.class, container, "id");
            converterMap.put("mlanguage", converter);
        }
        
        field = getField("participation");
        if (field instanceof AbstractSelect) {
            container = ((AbstractSelect) field).getContainerDataSource();
            converter = new BeanSetFieldPropertyConverter<Participation, Long>(Participation.class, container, "id");
            converterMap.put("participation", converter);
        }
        
        field = getField("award");
        if (field instanceof AbstractSelect) {
            container = ((AbstractSelect) field).getContainerDataSource();
            converter = new BeanSetFieldPropertyConverter<Award, Long>(Award.class, container, "id");
            converterMap.put("award", converter);
        }
    }

	public void configureValidators() {
        for (Object propertyId : getBeanPropertyIds()) {
            Field field = getField(propertyId);
            if (field != null) {
                Collection<Validator> validators = field.getValidators();
                if (validators != null) {
                    for (Validator validator : new ArrayList<Validator>(field.getValidators())) {
                        if (validator instanceof BeanValidationValidator || validator instanceof ConvertingValidator) {
                            field.removeValidator(validator);
                        }
                    }
                }
                BeanValidationValidator validator = new BeanValidationValidator(getEntityClass(), String.valueOf(propertyId));
                if (validator.isRequired()) {
                    field.setRequired(true);
                    field.setRequiredError(validator.getRequiredMessage());
                }
                PropertyConverter converter = getConverter(propertyId);
                if (converter == null) {
                    field.addValidator(validator);
                } else {
                    field.addValidator(new ConvertingValidator(validator, converter));
                }
            }
        }
    }

	public PropertyConverter getConverter(Object propertyId) {
        return converterMap.get(propertyId);
    }

	public BeanContainer<Long, MLanguage> getContainerForMLanguages() {
        BeanContainer<Long, MLanguage> container = new BeanContainer<Long, MLanguage>(MLanguage.class);
        container.setBeanIdProperty("id");
        for (MLanguage entity : MLanguage.findAllMLanguages()) {
            container.addBean(entity);
        }
        return container;
    }

	public BeanContainer<Long, Award> getContainerForAwards() {
        BeanContainer<Long, Award> container = new BeanContainer<Long, Award>(Award.class);
        container.setBeanIdProperty("id");
        for (Award entity : Award.findAllAwards()) {
            container.addBean(entity);
        }
        return container;
    }

	public BeanContainer<Long, Participation> getContainerForParticipations() {
        BeanContainer<Long, Participation> container = new BeanContainer<Long, Participation>(Participation.class);
        container.setBeanIdProperty("id");
        for (Participation entity : Participation.findAllParticipations()) {
            container.addBean(entity);
        }
        return container;
    }

	public Object getMLanguageCaptionPropertyId() {
        return null;
    }

	public Object getAwardCaptionPropertyId() {
        return null;
    }

	public Object getParticipationCaptionPropertyId() {
        return null;
    }

	public String getIdProperty() {
        return "id";
    }

	public String getVersionProperty() {
        return "version";
    }

	public void validateFields() {
        if (getItemDataSource() != null) {
            for (Object propertyId : getItemDataSource().getItemPropertyIds()) {
                Field field = getField(propertyId);
                if (field != null && !field.isReadOnly()) {
                    field.validate();
                }
            }
        }
    }

	public void commitFields() {
        if (getItemDataSource() != null) {
            for (Object propertyId : getItemDataSource().getItemPropertyIds()) {
                Field field = getField(propertyId);
                if (field != null && !field.isReadOnly()) {
                    field.commit();
                }
            }
        }
    }

	public void setFieldPropertyDataSource(Object propertyId, Property property) {
        Field field = getField(propertyId);
        if (field == null) {
            return;
        }
        if (property == null) {
            field.setPropertyDataSource(null);
        } else {
            PropertyConverter converter = getConverter(propertyId);
            if (converter != null) {
                converter.setPropertyDataSource(property);
                field.setPropertyDataSource(converter);
            } else {
                if (field instanceof CheckBox && property.getValue() == null) {
                    property.setValue(Boolean.FALSE);
                }
                field.setPropertyDataSource(property);
            }
        }
    }

	public void setFieldValues(Item item) {
        if (item != null) {
            // set values for fields in item
            for (Object propertyId : item.getItemPropertyIds()) {
                setFieldPropertyDataSource(propertyId, item.getItemProperty(propertyId));
            }
            // other fields are not touched by default
        } else {
            // reset all fields
            for (Object propertyId : getBeanPropertyIds()) {
                setFieldPropertyDataSource(propertyId, null);
            }
        }
    }

	public Field getFirstField() {
        Iterator<Object> it = getBeanPropertyIds().iterator();
        if (it.hasNext()) {
            return getField(it.next());
        }
        return null;
    }

	public Class<Movie> getEntityClass() {
        return Movie.class;
    }
}
