// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package entity.select;

import java.lang.String;

privileged aspect MLanguage_Roo_JavaBean {
    
    public String MLanguage.getTitle() {
        return this.title;
    }
    
    public void MLanguage.setTitle(String title) {
        this.title = title;
    }
    
}
